# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
#
# Configure Using Gemfile
# gem "pg"

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1
  port: 5432

development:
  <<: *default
  database: todududu_development
  username: rittt
  password:

test:
  <<: *default
  database: todududu_test
  username: rittt
  password:

production:
  primary: &primary
    url: <%= ENV["DATABASE_URL"] %>

  queue:
    <<: *primary

  cache:
    <<: *primary

  cable:
    <<: *primary


